FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

#Copy everything
COPY ./Api ./Api
COPY ./Infrastructure ./Infrastructure
COPY ./Core ./Core

WORKDIR /App/Api

#rESTORE AS DISTINCT LAYERS
RUN dotnet restore 
#Build and publish a release
RUN dotnet publish -c Release -o out



#Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App/Api
COPY --from=build-env /App/Api/out .

#EXPOR A PORTA PARA INTERNET
EXPOSE 8080

ENTRYPOINT ["dotnet", "TechChallangeCadastroContatosAPI.dll"]