apiVersion: v1
kind: Pod
metadata:
  name: fiap-consumidor
  labels:
    app: fiap-consumidor
spec:
  containers:
    - name: fiap-consumidor
      image: consumidor:v1
      ports:
        - containerPort: 8080
      env:
        - name: "CONNECTIONSTRINGS__CONNECTIONSTRING"
          value: "Server=svc-sql,1433;Database=HealthMedDb;User ID=sa;Password=Passw0rd;TrustServerCertificate=True;"
        - name: "MassTransit__Servidor"
          value: "svc-mensageria"
