apiVersion: v1
kind: Pod
metadata:
  name: fiap-sql
  labels:
    app: fiap-sql
spec:
 # securityContext:
 #   fsGroup: 10001  # Isso garante que o usuário mssql tenha acesso ao volume
  containers:
    - name: sql
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
      env:
        - name: "ACCEPT_EULA"
          value: "Y"
        - name: "MSSQL_SA_PASSWORD"
          value: "Passw0rd"
        - name: MSSQL_PID
          value: "Developer"
  securityContext:
    runAsUser: 10001
    fsGroup: 10001

