apiVersion: v1
kind: Pod
metadata:
  name: fiap-mensageria
  labels:
    app: fiap-mensageria
spec:
  containers:
    - name: rabbitmq
      image: masstransit/rabbitmq
      ports:
        - containerPort: 5672
        - containerPort: 15672