apiVersion: v1
kind: Service
metadata:
  name: svc-sql
  labels:
    app: svc-sql

spec:
  type: NodePort
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
      nodePort: 32200

  selector:
    app: fiap-sql